steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:latest'
      - '.'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'buhler-roi-calculator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'BASIC_AUTH_USER=buhler,BASIC_AUTH_PASSWORD=demo2025,NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/buhler-roi-calculator:latest'

options:
  logging: CLOUD_LOGGING_ONLY